### ISSUE TITLE
Syntax error with block-scoped declarations not being supported outside of strict mode

### ISSUE THREAD

**Issue by squashytaur** [minemidnight/eris-additions#1]
Exactly as the title says.
Freshly installed eris-additions using **npm install eris-additions**.
I am running node.js 8.1.3, npm 2.15.11 and I am using nodemon 1.11.0.

Here is the error on Pastebin: https://pastebin.com/hYTbj9Cx
Here is the raw error:
```
/home/ubuntu/workspace/node_modules/eris-additions/index.js:8
let loadedAdditions = [];
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/workspace/start.js:1:74)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
[nodemon] app crashed - waiting for file changes before starting...

```
Any help would be appreciated.

**Comment by bjxke** [comment]
You need to update node.

**Comment by LJNeon** [comment]
Just tested it myself in the same version and it works for me. That error is thrown in node v6 so I think you got your node versions confused.

**Comment by bjxke** [comment]
Needs node 7 upper

**Comment by minemidnight** [comment]
Outdated node version.
