### ISSUE TITLE
Error on Channel.awaitMessages()

### ISSUE THREAD

**Issue by exoRift** [minemidnight/eris-additions#11]
```
TypeError: this.filter is not a function
    at MessageCollector.verify (C:\Users\REDACTED\Documents\GitHub\gaijin\node_modules\eris-additions\lib\Channel\awaitMes
sages.js:19:11)
    at Client.MessageCollector.listener.message (C:\Users\REDACTED\Documents\GitHub\gaijin\node_modules\eris-additions\lib
\Channel\awaitMessages.js:12:35)
    at emitOne (events.js:121:20)
    at Client.emit (events.js:211:7)
    at Shard.emit (C:\Users\REDACTED\Documents\GitHub\gaijin\node_modules\eris\lib\gateway\Shard.js:1888:26)
    at Shard.wsEvent (C:\Users\REDACTED\Documents\GitHub\gaijin\node_modules\eris\lib\gateway\Shard.js:421:26)
    at Shard.onWSMessage (C:\Users\REDACTED\Documents\GitHub\gaijin\node_modules\eris\lib\gateway\Shard.js:1727:26)
    at WebSocket.ws.onmessage (C:\Users\REDACTED\Documents\GitHub\gaijin\node_modules\eris\lib\gateway\Shard.js:1605:33)
    at WebSocket.onMessage (C:\Users\REDACTED\Documents\GitHub\gaijin\node_modules\ws\lib\event-target.js:120:16)
    at emitOne (events.js:116:13)
    at WebSocket.emit (events.js:211:7)
    at Receiver.receiverOnMessage (C:\Users\REDACTED\Documents\GitHub\gaijin\node_modules\ws\lib\websocket.js:719:20)
    at emitOne (events.js:116:13)
    at Receiver.emit (events.js:211:7)
    at Receiver.dataMessage (C:\Users\REDACTED\Documents\GitHub\gaijin\node_modules\ws\lib\receiver.js:414:14)
    at Receiver.getData (C:\Users\REDACTED\Documents\GitHub\gaijin\node_modules\ws\lib\receiver.js:346:17)```

**Comment by minemidnight** [comment]
You have to provide a filter when collecting messages. Thread closed, but you can continue replying if you want help.
